# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/conf.py

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: doc/requirements.txt
build:
   os: ubuntu-22.04
   tools:
      python: "3.10"


